## Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [4]:
matrix = tf.constant([[1,2],[3,2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 2]], dtype=int32)>

In [5]:
matrix.ndim

2

In [6]:
vector.ndim

1

In [7]:
scalar.ndim

0

### Creating tensors with tf.Variable

In [8]:
variable_tensor = tf.Variable([5,6])
constant_tensor = tf.constant([5,6])
variable_tensor, constant_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 6], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>)

In [9]:
# assign function
variable_tensor[1].assign(8)
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 8], dtype=int32)>

In [10]:
variable_tensor[0] = 6

TypeError: ignored

In [11]:
constant_tensor[0].assign(8)

AttributeError: ignored

### Creating random tensors

In [12]:
random_tensor1 = tf.random.Generator.from_seed(121)       #set the seed
random_tensor1 = random_tensor1.normal(shape=(3,3))

random_tensor2 = tf.random.Generator.from_seed(121)
random_tensor2= random_tensor2.normal(shape=(3,3))

random_tensor1, random_tensor2, random_tensor1 == random_tensor2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-2.3299215 ,  0.26317742,  0.5479082 ],
        [-0.11180725,  0.82159203,  0.6540846 ],
        [ 0.08996315, -2.073694  ,  0.8673864 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-2.3299215 ,  0.26317742,  0.5479082 ],
        [-0.11180725,  0.82159203,  0.6540846 ],
        [ 0.08996315, -2.073694  ,  0.8673864 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [13]:
random_tensor3 = tf.random.Generator.from_seed(12)
random_tensor3 = random_tensor3.normal(shape=(3,3))
random_tensor2, random_tensor3, random_tensor2==random_tensor3

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-2.3299215 ,  0.26317742,  0.5479082 ],
        [-0.11180725,  0.82159203,  0.6540846 ],
        [ 0.08996315, -2.073694  ,  0.8673864 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-1.0130816 ,  0.28291714,  1.2132233 ],
        [ 0.46988967,  0.37944323, -0.6664026 ],
        [ 0.6054596 ,  0.19181173,  0.8045827 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False],
        [False, False, False]])>)

### Shuffling the tensor

In [14]:
not_shuffled_tensor = tf.constant([[2,3],[3,4],[5,6]])
not_shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4],
       [5, 6]], dtype=int32)>

In [15]:
tf.random.shuffle(not_shuffled_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4],
       [5, 6]], dtype=int32)>

In [19]:
tensor1 = tf.random.Generator.from_seed(123)
tensor1= tensor1.normal(shape=(3,3))
tensor1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.8673864 , -0.29899067, -0.9310337 ],
       [-1.5828488 ,  1.2481191 , -0.6770643 ],
       [ 0.0191265 , -0.29333332, -0.35438988]], dtype=float32)>

### Aggregating Tensors

In [20]:
tensor_agg = tf.constant([[1,-2,-3],[-4,-5,6],[7,8,-9]])
tensor_agg

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [21]:
tf.abs(tensor_agg)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [23]:
tensor_agg

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [25]:
import numpy as np
tensor_rand1 = tf.constant(np.random.randint(0,100,size =50))
tensor_rand1

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([23, 36, 25, 35, 28, 99, 49, 22, 26, 69, 65, 70,  9, 37, 51, 66, 41,
       13, 18, 62,  9, 78, 13, 22, 74, 41,  2, 45,  5, 91,  8, 94, 21, 96,
       92, 53,  1, 46, 91, 17, 67, 41,  7, 55, 28, 69, 70, 47, 47, 24])>

In [26]:
tf.reduce_min(tensor_rand1)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [27]:
tf.reduce_max(tensor_rand1)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [34]:
tensor_rand1 = tf.reshape(tensor_rand1, [10,5])
tensor_rand1

<tf.Tensor: shape=(10, 5), dtype=int64, numpy=
array([[23, 36, 25, 35, 28],
       [99, 49, 22, 26, 69],
       [65, 70,  9, 37, 51],
       [66, 41, 13, 18, 62],
       [ 9, 78, 13, 22, 74],
       [41,  2, 45,  5, 91],
       [ 8, 94, 21, 96, 92],
       [53,  1, 46, 91, 17],
       [67, 41,  7, 55, 28],
       [69, 70, 47, 47, 24]])>

In [35]:
tf.reduce_min(tensor_rand1)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [36]:
tf.reduce_mean(tensor_rand1)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [40]:
tf.reduce_mean(tensor_rand1, keepdims = True)

<tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[43]])>

In [45]:
tf.math.reduce_variance(tf.cast(tensor_rand1, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=780.35846>

In [48]:
import tensorflow_probability as tfp
tfp.stats.variance(tensor_rand1, sample_axis = None)

<tf.Tensor: shape=(), dtype=int64, numpy=781>

In [49]:
tf.math.reduce_std(tf.cast(tensor_rand1, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.934896>

In [52]:
tfp.stats.stddev(tf.cast(tensor_rand1, dtype= tf.float32), sample_axis=None)

<tf.Tensor: shape=(), dtype=float32, numpy=27.934896>

In [53]:
tf.math.argmax(tensor_rand1, axis = None)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 6, 9, 6, 6])>

In [54]:
tf.math.argmax(tensor_rand1, axis = 1)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([1, 0, 1, 0, 1, 4, 3, 3, 0, 1])>

In [55]:
tf.math.argmax(tensor_rand1, axis =0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 6, 9, 6, 6])>

In [57]:
tensor_rand1[tf.math.argmax(tensor_rand1,axis=None)]

TypeError: ignored

InvalidArgumentError: ignored